[versions]
agp = "8.7.1"
xposed = "82"
kotlin = "1.9.22"

[libraries]
xposed-api = { module = "de.robv.android.xposed:api", version.ref = "xposed" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }

